<?php
/**
 * GoodNews
 *
 * Copyright 2012 by bitego <office@bitego.com>
 *
 * GoodNews is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * GoodNews is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this software; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA
 */

/**
 * GoodNews default
 *
 * @package goodnews
 * @subpackage lexicon
 * @language fr
 */

$_lang['goodnews']                                                  = 'GoodNews';
$_lang['goodnews.desc']                                             = 'Un système intégré d\'envoi de newsletter et de groupes.';
$_lang['goodnews.version']                                          = 'Version GoodNews';
$_lang['goodnews.credits']                                          = 'Crédits';
$_lang['goodnews.credits_modx_community']                           = 'Un grand merci à l\'étonnante communauté MODX pour leur aide infatigable!';
$_lang['goodnews.credits_bob_ray']                                  = 'Méthodes pour convertir les styles d\'image inline par Bob Ray- <a href="http://bobsguides.com">http://bobsguides.com</a>';
$_lang['goodnews.credits_icons_by']                                 = 'Icones sous Revo 2.2.x par :FatCow Web Hosting - <a href="http://www.fatcow.com">http://www.fatcow.com</a>';
$_lang['goodnews.system_checks']                                    = 'Contrôles du système';
$_lang['goodnews.system_check_title']                               = 'Titre';
$_lang['goodnews.system_check_value']                               = 'Valeur (Statuts)';
$_lang['goodnews.multi_processing_for_sending']                     = 'Multi-traitement pour l\'envoi de mails disponible';
$_lang['goodnews.imap_extension_available']                         = 'Extension IMAP disponible (Gestion des rebonds (Bounce Handling))';
$_lang['goodnews.pthumb_addon_installed']                           = 'MODX Add-On: pThumb installé (règle automatiquement la taille des images)';
$_lang['goodnews.php_version_required']                             = 'Version PHP requise: ';
$_lang['goodnews.site_status']                                      = 'Le site est publié sur le web';
$_lang['goodnews.debug_mode']                                       = 'GoodNews mode debug';
$_lang['goodnews.activated']                                        = 'Activaté';
$_lang['goodnews.deactivated']                                      = 'Désactivé';
$_lang['goodnews.on']                                               = 'ON';
$_lang['goodnews.off']                                              = 'OFF';
$_lang['goodnews.start']                                            = 'Start';
$_lang['goodnews.stop']                                             = 'Stop';
$_lang['goodnews.continue']                                         = 'Continue';
$_lang['goodnews.test']                                             = 'Test';
$_lang['goodnews.sendlog']                                          = 'Voir Log';
$_lang['goodnews.id']                                               = 'ID';
$_lang['goodnews.modx_username']                                    = 'MODX Username';
$_lang['goodnews.management']                                       = 'GoodNews - Group Mailer';
$_lang['goodnews.button_settings']                                  = 'Paramètres';
$_lang['goodnews.input_search_filter']                              = 'Filtre de recherche...';
$_lang['goodnews.button_filter_clear']                              = 'Réinitialiser';
$_lang['goodnews.msg_loading']                                      = 'Chargement...';
$_lang['goodnews.msg_saving']                                       = 'Enregistrement...';
$_lang['goodnews.msg_saving_successfull']                           = 'Les paramètres système modifiés sont sauvegardés.';
$_lang['goodnews.msg_failed']                                       = 'Echoué';
$_lang['goodnews.choose_container']                                 = 'Choisir le conteneur du Mailing';
$_lang['goodnews.container_switching']                              = 'Changer le conteneur du Mailing';

$_lang['goodnews.mail_plaintext_preview']                           = 'Prévisualisation du mail en texte brut';
$_lang['goodnews.mail_subject']                                     = 'Sujet du Mailing';
$_lang['goodnews.mail_body']                                        = 'Corps du Mailing';

$_lang['goodnews.newsletters']                                      = 'Mailings';
$_lang['goodnews.newsletters_management_desc']                      = 'Gérez vos mailings de tous les conteneurs GoodNews ici. La grille présente les informations de statuts des documents Mail de groupe et Newsletter. Pour afficher des informations supplémentaires, cliquer sur l\'icone email. Pour recevoir des informations en direct pendant l\'envoi, activer <strong>Auto-Refresh</strong>.';
$_lang['goodnews.newsletter_create']                                = 'Créer un Mailing';
$_lang['goodnews.newsletter_id']                                    = 'ID';
$_lang['goodnews.newsletter_title']                                 = 'Titre du Mailing';
$_lang['goodnews.newsletter_sender']                                = 'Envoyé par';
$_lang['goodnews.newsletter_sent_on']                               = 'Envoyé le';
$_lang['goodnews.newsletter_finished_on']                           = 'Terminé le';
$_lang['goodnews.newsletter_categories']                            = 'Catégories';
$_lang['goodnews.newsletter_recipients']                            = 'Destinataires: ';
$_lang['goodnews.newsletter_recipients_sent']                       = 'Destinataires / Envoyé';
$_lang['goodnews.newsletter_sending_errors']                        = 'Envoi des erreurs';
$_lang['goodnews.newsletter_status']                                = 'Statut';
$_lang['goodnews.newsletter_status_finished']                       = 'Envoyé';
$_lang['goodnews.newsletter_status_stopped']                        = 'Arrêté';
$_lang['goodnews.newsletter_status_in_progress']                    = 'Envoi ...';
$_lang['goodnews.newsletter_status_not_yet_sent']                   = 'Pas Envoyé';
$_lang['goodnews.newsletter_status_not_ready_to_send']              = 'Incomplet';
$_lang['goodnews.newsletter_status_not_published']                  = 'Pas publié';
$_lang['goodnews.newsletter_status_scheduled']                      = 'Scheduled';
$_lang['goodnews.newsletter_statusemail_subject_prefix']            = 'Mailing Status Report: ';
$_lang['goodnews.newsletter_sent_scheduled']                        = 'Sent scheduled';
$_lang['goodnews.newsletter_createdby']                             = 'Créé by';
$_lang['goodnews.newsletter_createdon']                             = 'Créé le';
$_lang['goodnews.newsletter_publishedby']                           = 'Publié par';
$_lang['goodnews.newsletter_publishedon']                           = 'Publié on';
$_lang['goodnews.newsletter_scheduled']                             = 'Scheduled';
$_lang['goodnews.newsletter_soft_bounces']                          = 'Erreur temporaire';
$_lang['goodnews.newsletter_hard_bounces']                          = 'Erreur définitive';
$_lang['goodnews.newsletter_testrecipients']                        = 'Destinataire test';
$_lang['goodnews.newsletter_no_testrecipients']                     = 'Aucun Destinataire test défini.';
$_lang['goodnews.newsletter_filter']                                = 'Filtre Mailing...';
$_lang['goodnews.newsletter_filter_all']                            = 'Tous les Mailings';
$_lang['goodnews.newsletter_filter_scheduled']                      = 'Programmé';
$_lang['goodnews.newsletters_none']                                 = 'Aucun mailing';
$_lang['goodnews.newsletter_prepare']                               = 'Préparer le Mailing';
$_lang['goodnews.newsletter_view']                                  = 'Voir le Mail';
$_lang['goodnews.newsletter_preview']                               = 'Prévisualiser le Mail';
$_lang['goodnews.newsletter_publish']                               = 'Publier le Mailing';
$_lang['goodnews.newsletter_unpublish']                             = 'Dépublier le Mailing';
$_lang['goodnews.newsletter_test_send']                             = 'Mailing Test';
$_lang['goodnews.newsletter_test_send_confirm']                     = 'Envoyer le Mailing Test maintenant?';
$_lang['goodnews.newsletter_sending_test']                          = 'Envoi du Mailing Test en cours';
$_lang['goodnews.newsletter_finished_sending_test']                 = 'Envoi du Mailing Test terminé.';
$_lang['goodnews.newsletter_start_sending']                         = 'Démarrer l\'envoi du Mailing';
$_lang['goodnews.newsletter_start_sending_confirm']                 = 'Envoyer le Mailing maintenant?';
$_lang['goodnews.newsletter_sending']                               = 'Envoi du Mailing en cours';
$_lang['goodnews.newsletter_stop_sending']                          = 'Arrêter l\'envoi du Mailing';
$_lang['goodnews.newsletter_stop_sending_confirm']                  = 'Arrêter l\'envoi du Mailing maintenant? L\'envoi peut être reprise n\'importe quand.';
$_lang['goodnews.newsletter_continue_sending']                      = 'Reprendre l\'envoi du Mailing';
$_lang['goodnews.newsletter_continue_sending_confirm']              = 'Reprendre l\'envoi du Mailing maintenant?';
$_lang['goodnews.newsletter_remove']                                = 'Supprimer le Mailing';
$_lang['goodnews.newsletter_undelete']                              = 'Restaurer le Mailing';
$_lang['goodnews.newsletter_update']                                = 'Editer le Mailing';
$_lang['goodnews.newsletter_remove_confirm']                        = 'Etes-vous sûr de vouloir supprimer ce Mailing?';
$_lang['goodnews.newsletter_draft']                                 = '(Brouillon)';
$_lang['goodnews.newsletter_cat_not_defined']                       = '(aucune sélection)';
$_lang['goodnews.newsletter_cat_assign']                            = 'Assigner des catégories de mailing';
$_lang['goodnews.newsletter_cat_assign_desc']                       = 'Les destinataires sont assortis.';
$_lang['goodnews.newsletter_send_process']                          = 'Processus d\'envoi: ';
$_lang['goodnews.newsletter_send_process_started']                  = 'Processus entamés';
$_lang['goodnews.newsletter_send_process_started_msg_success']      = 'Les processus d\'envoi ont été activés!';
$_lang['goodnews.newsletter_send_process_started_msg_failed']       = 'Les processus d\'envoi n\'ont pas pu être activés!';
$_lang['goodnews.newsletter_send_process_stopped']                  = 'Processus arrêtés';
$_lang['goodnews.newsletter_send_process_stopped_msg_success']      = 'Tous les processus d\'envoi ont été désactivés!';
$_lang['goodnews.newsletter_send_process_stopped_msg_failed']       = 'Les processus d\'envoi n\'ont pas pu être désactivés!';
$_lang['goodnews.newsletter_grid_autorefresh']                      = 'Auto-Refresh: ';
$_lang['goodnews.newsletter_sendlog_view']                          = 'Voir Log d\'envoi';
$_lang['goodnews.newsletter_sendlog_window_title']                  = 'Envoyer les Logs pour le Mailing: ';
$_lang['goodnews.newsletter_sendlog_export_button']                 = 'Export';
$_lang['goodnews.newsletter_sendlog_close_button']                  = 'Close';
$_lang['goodnews.newsletter_err_save_already_sending']              = 'Les modifications ne peuvent pas être sauvegardées , car l\'envoi de ce mailing a déjà débuté.';

$_lang['goodnews.sendlog_subscriber_email']                         = 'Subscriber (Email)';
$_lang['goodnews.sendlog_subscriber_fullname']                      = 'Subscriber (Name)';
$_lang['goodnews.sendlog_statustime']                               = 'Status-Time';
$_lang['goodnews.sendlog_status']                                   = 'Status';
$_lang['goodnews.sendlog_status_filter']                            = 'Filter by Status...';
$_lang['goodnews.sendlog_status_sent']                              = 'Sent';
$_lang['goodnews.sendlog_status_send_error']                        = 'Send error';
$_lang['goodnews.sendlog_status_unknown']                           = 'Unknown';
$_lang['goodnews.sendlog_none']                                     = 'No send-log entries';

$_lang['goodnews.groups']                                           = 'Groupes';
$_lang['goodnews.groups_management_desc']                           = 'Gérez vos groupes d\'inscrits ici. Assigner un groupe GoodNews à un groupe d\'utilisateurs MODX (<span class="gon-modx-group-assigned">Marker bleu</span>), rend possible d\'envoyer des mailings à tous les membres de ce groupe d\'utilisateurs MODX. Si vous assignez un groupe d\'utilisateurs MODX, ce groupe GoodNews <strong>ne peut pas</strong> être utilisé pour gérer les inscrits.';
$_lang['goodnews.group_create']                                     = 'Créer Groupe';
$_lang['goodnews.modx_groups_edit']                                 = 'Editer les groupes d\'utilisateurs MODX';
$_lang['goodnews.group_name']                                       = 'Nom du groupe';
$_lang['goodnews.group_description']                                = 'Description';
$_lang['goodnews.group_membercount']                                = 'Inscrits';
$_lang['goodnews.modx_usergroup']                                   = 'Groupe d\'utilisateurs MODX';
$_lang['goodnews.group_belongs_to_modx_usergroup']                  = 'Assigné au groupe d\'utilisateurs MODX';
$_lang['goodnews.choose_modx_user_group']                           = '(Choisir le groupe d\'utilisateurs MODX)';
$_lang['goodnews.group_public']                                     = 'Public';
$_lang['goodnews.groups_none']                                      = 'Aucun groupe';
$_lang['goodnews.group_remove']                                     = 'Supprimer le groupe';
$_lang['goodnews.group_update']                                     = 'Editer le groupe';
$_lang['goodnews.group_remove_confirm']                             = 'Etes-vous sûr de vouloir supprimer ce groupe?<br /><br />Supprimer un groupe supprime aussi toutes ses catégories relatives. De plus, cela désinscrit tous les inscrits de ce groupes et catégories relatives. <br /><br /><strong>Cela ne peut être annulé!</strong>';
$_lang['goodnews.group_err_ns_name']                                = 'Merci de spécifier un nom pour ce ce groupe.';
$_lang['goodnews.group_err_ae']                                     = 'Un groupe avec ce nom existe déjà.';
$_lang['goodnews.group_modxgroup_err_ae']                           = 'Ce groupe d\'utilisateurs MODX est déjà assigné à un autre groupe.';
$_lang['goodnews.group_err_nf']                                     = 'Groupe introuvable.';
$_lang['goodnews.group_err_ns']                                     = 'Groupe non spécifié.';
$_lang['goodnews.group_err_remove']                                 = 'Une erreur s\'est produite lors de la suppression du groupe.';
$_lang['goodnews.group_err_save']                                   = 'Une erreur s\'est produite lors de la sauvegarde du groupe.';
                                                            
$_lang['goodnews.category']                                         = 'Catégorie';
$_lang['goodnews.categories']                                       = 'Catégories';
$_lang['goodnews.categories_management_desc']                       = 'Gérer vos catégories de mailing ici.';
$_lang['goodnews.category_create']                                  = 'Créer une catégorie';
$_lang['goodnews.category_name']                                    = 'Nom de la catégorie';
$_lang['goodnews.category_description']                             = 'Description';
$_lang['goodnews.category_membercount']                             = 'Inscrits';
$_lang['goodnews.category_usergroup']                               = 'Groupe';
$_lang['goodnews.category_belongs_to_usergroup']                    = 'Appartient au groupe';
$_lang['goodnews.category_public']                                  = 'Public';
$_lang['goodnews.categories_none']                                  = 'Aucune catégorie';
$_lang['goodnews.category_remove']                                  = 'Supprimer la catégorie';
$_lang['goodnews.category_update']                                  = 'Editer la catégorie';
$_lang['goodnews.category_remove_confirm']                          = 'Etes-vous sûr de vouloir supprimer cette catégorie?<br /><br />Supprimer une catégorie désinscrit tous ses inscrits.<br /><br /><strong>Cela ne peut être annulé!</strong>';
$_lang['goodnews.category_err_ns_name']                             = 'Merci de donner un nom à la catégorie.';
$_lang['goodnews.category_err_ns_group']                            = 'Choisir un groupe pour la catégorie.';
$_lang['goodnews.category_err_ae']                                  = 'Une catégorie portant ce nom existe déjà.';
$_lang['goodnews.category_err_nf']                                  = 'Catégorie introuvable.';
$_lang['goodnews.category_err_ns']                                  = 'Catégorie non spécifiée.';
$_lang['goodnews.category_err_remove']                              = 'Une erreur s\'est produite lors de la suppression de la catégorie.';
$_lang['goodnews.category_err_save']                                = 'Une erreur s\'est produite lors de la sauvegarde de la catégorie.';
                                                            
$_lang['goodnews.subscribers']                                      = 'Inscrits';
$_lang['goodnews.subscribers_desc']                                 = 'Gérer vos inscrits ici. Les nouveaux inscrits sont créés à travers les inscriptions utilisateur, ou manuellement via la gestion utilisateur MODX ou encore par import.';
$_lang['goodnews.modx_user_create']                                 = 'Créer un utilisateur MODX';
$_lang['goodnews.subscribers_user_group']                           = 'Groupe d\'inscrits';
$_lang['goodnews.subscribers_user_group_filter']                    = 'Filtrer par groupe...';
$_lang['goodnews.subscribers_user_category_filter']                 = 'Filtrer par catégorie...';
$_lang['goodnews.subscribers_choose_user_group']                    = '(choisir le groupe d\'inscrits)';
$_lang['goodnews.subscriber_username']                              = 'Nom d\'utilisateur';
$_lang['goodnews.subscriber_groups_categories']                     = 'Groupe d\'inscrits et catégories';
$_lang['goodnews.subscriber_groups_categories_multi']               = 'Available Groups and Categories';
$_lang['goodnews.subscriber_fullname']                              = 'Nom complet';
$_lang['goodnews.subscriber_email']                                 = 'Email';
$_lang['goodnews.subscriber_mailing_groups']                        = 'Groupes de Mailing';
$_lang['goodnews.subscriber_mailing_categories']                    = 'Catégories de Mailing';
$_lang['goodnews.subscriber_subscribed_on']                         = 'Abonné depuis';
$_lang['goodnews.subscriber_activated_on']                          = 'Activé depuis';
$_lang['goodnews.subscriber_active']                                = 'Actif';
$_lang['goodnews.subscriber_testdummy']                             = 'Tester';
$_lang['goodnews.subscriber_ip']                                    = 'L\'inscription IP';
$_lang['goodnews.subscriber_ip_activated']                          = 'L\'activation IP';
$_lang['goodnews.subscriber_ip_unknown']                            = 'inconnu';
$_lang['goodnews.subscriber_ip_imported']                           = 'importé';
$_lang['goodnews.subscriber_ip_manually']                           = 'manuellement';
$_lang['goodnews.subscriber_soft_bounces']                          = 'SB';
$_lang['goodnews.subscriber_hard_bounces']                          = 'HB';
$_lang['goodnews.subscriber_testdummy_filter']                      = 'Destinataire test?';
$_lang['goodnews.subscriber_active_filter']                         = 'Activé?';
$_lang['goodnews.subscriber_select_as_testdummy']                   = 'L\'inscrit est le destinataire des tests.';
$_lang['goodnews.subscriber_select_as_testdummy_multi']             = 'Subscribers are recipients of test-mailings and newsletters';
$_lang['goodnews.subscribers_none']                                 = 'Aucun inscrit';
$_lang['goodnews.subscribers_no_group']                             = 'Aucun groupe assigné';
$_lang['goodnews.subscribers_no_category']                          = 'Aucun catégorie assigné';
$_lang['goodnews.subscriber_update']                                = 'Editer les Souscriptions';
$_lang['goodnews.subscriber_remove_subscriptions']                  = 'Supprimer toutes les Souscriptions';
$_lang['goodnews.subscriber_remove_subscriptions_confirm']          = 'Etes-vous sûr de vouloir supprimer toutes les souscriptions de cet utilisateur ?';
$_lang['goodnews.subscriber_remove_meta_data']                      = 'Supprimer toutes les Meta-Data GoodNews';
$_lang['goodnews.subscriber_remove_meta_data_confirm']              = 'Etes-vous sûr de vouloir supprimer toutes les Meta-Data GoodNews de cet utilisateur ?';
$_lang['goodnews.subscriber_reset_bounce_counters']                 = 'Réinitialiser les compteurs de Rebond';
$_lang['goodnews.subscriber_reset_bounce_counters_confirm']         = 'Etes-vous sûr de vouloir réinitialiser tous les compteurs de Rebond de cet utilisateur ?';
$_lang['goodnews.user_update']                                      = 'Editer l\'utilisateur (Table Utilisateur MODX)';
$_lang['goodnews.subscriber_assign_multi']                          = 'Assign Subscriptions to Selected';
$_lang['goodnews.subscriber_remove_multi']                          = 'Remove Subscriptions from Selected';
$_lang['goodnews.subscriber_remove_subscriptions_multi']            = 'Remove All Subscriptions from Selected';
$_lang['goodnews.subscriber_remove_subscriptions_confirm_multi']    = 'Are you sure you want to remove all subscriptions from selected users?';
$_lang['goodnews.subscriber_remove_meta_data_multi']                = 'Remove All GoodNews Meta-Data from Selected';
$_lang['goodnews.subscriber_remove_meta_data_confirm_multi']        = 'Are you sure you want to remove all GoodNews meta-data from selected users?';
$_lang['goodnews.subscriber_reset_bounce_counters_multi']           = 'Reset Bounce Counters of Selected';
$_lang['goodnews.subscriber_reset_bounce_counters_confirm_multi']   = 'Are you sure you want to reset all bounce counters of selected users?';
$_lang['goodnews.subscriber_err_ns_multi']                          = 'You need to select at least one subscriber.';
$_lang['goodnews.subscriber_button_save_replace']                   = 'Replace all';
$_lang['goodnews.subscriber_button_save_add']                       = 'Add';
$_lang['goodnews.subscriber_button_save_remove']                    = 'Remove';

$_lang['goodnews.settings']                                         = 'GoodNews - Paramètres';
$_lang['goodnews.settings_save_button']                             = 'Sauvegarder les Paramètres';
$_lang['goodnews.settings_close_button']                            = 'Fermer';
$_lang['goodnews.settings_general_tab']                             = 'Général';
$_lang['goodnews.settings_general_tab_desc']                        = 'Gérer les Paramètres généraux de GoodNews ici.';
$_lang['goodnews.settings_container_tab']                           = 'Conteneur';
$_lang['goodnews.settings_container_tab_desc']                      = 'Gérer les paramètres protégés de vos conteneurs de ressource GoodNews ici La grille liste les conteneurs GoodNews disponibles de l\'arbre des ressources.';
$_lang['goodnews.settings_bounceparsingrules_tab']                  = 'Règles d\'analyse des Rebonds';
$_lang['goodnews.settings_bounceparsingrules_tab_desc']             = 'Gérer ici les règles pour analyser les Messages-Rebond.';
$_lang['goodnews.settings_system_tab']                              = 'Système';
$_lang['goodnews.settings_system_tab_desc']                         = 'Gérer ici les paramètres système GoodNews.';
$_lang['goodnews.settings_about_tab']                               = 'A propos de GoodNews';
$_lang['goodnews.settings_about_tab_desc']                          = 'Informations système GoodNews.';
$_lang['goodnews.settings_test_subject_prefix']                     = 'Préfixe pour le Sujet des Tests de Mailing';
$_lang['goodnews.settings_test_subject_prefix_desc']                = 'Définir un texte qui sera préfixé au Sujet des Tests de Mailing. Define a text which will be prefixed to test-mailing subjects.';
$_lang['goodnews.settings_statusemail_enabled']                     = 'Status-Reports activated';
$_lang['goodnews.settings_statusemail_enabled_desc']                = 'Whether or not status-reports will be sent if mailing-status changes (stopped or finished).';
$_lang['goodnews.settings_statusemail_fromname']                    = 'Name of the Sender for Status-Emails';
$_lang['goodnews.settings_statusemail_fromname_desc']               = 'Define a Name which is used for sending status-emails.';
$_lang['goodnews.settings_statusemail_chunk']                       = 'Chunk for Status-Emails';
$_lang['goodnews.settings_statusemail_chunk_desc']                  = 'Define a Chunk which is used for sending status-emails.';
$_lang['goodnews.settings_mailing_bulk_size']                       = 'Taille du lot du Mailing (1-100)';
$_lang['goodnews.settings_mailing_bulk_size_desc']                  = 'Définit combien d\'emails sont envoyés par un processus.';
$_lang['goodnews.settings_mails_per_bulk']                          = 'Emails par lot';
$_lang['goodnews.settings_worker_process_limit']                    = 'Nombre maximal de processus d\'envoi(1-10)';
$_lang['goodnews.settings_worker_process_limit_desc']               = 'Définit le nombre maximal de processus parallèles d\'envoi à utiliser. Si vous déplacez le curseur à 1, le multitraitement sera désactivé et le processus d\'envoi par défaut sera utilisé à la place.';
$_lang['goodnews.settings_process_max']                             = ' processus max.';
$_lang['goodnews.settings_multiprocessing_disabled']                = 'multitraitement désactivé';
$_lang['goodnews.settings_worker_process_active']                   = 'Processus d\'envoi activé';
$_lang['goodnews.settings_worker_process_active_desc']              = 'ce paramètre peut être utilisé pour désactiver le processus d\'envoi. Cela signifie qu\'un planificateur de tâches comme Cron ne peut déclencher un nouveau processus';
$_lang['goodnews.settings_cron_security_key']                       = 'Clé de Sécurité Cron';
$_lang['goodnews.settings_cron_security_key_desc']                  = 'S\'il vous plaît, entrez une chaîne (comme un mot de passe) aléatoire qui sera utilisée pour l\'authentification CLI Cron. Vous devez configurer votre tâche planifiée Cron  avec le paramètre CLI supplémentaires <strong> sid = [votre clé de sécurité cron] </ strong>. Il est fortement recommandé d\'ajouter une clé pour des raisons de sécurité. Laissez ce champ vide, si vous n\'avez aucune possibilité de configurer votre tâche Cron avec un paramètre supplémentaire.';
$_lang['goodnews.settings_admin_groups']                            = 'Groupes Administrateur GoodNews';
$_lang['goodnews.settings_admin_groups_desc']                       = 'Liste des groupes d\'utilisateurs MODX séparés par une virgule, qui ont accès aux paramètres GoodNews.';
$_lang['goodnews.settings_auto_fix_imagesizes']                     = 'Ajuster automatiquement la taille des images (pThumb Extra nécessaire)';
$_lang['goodnews.settings_auto_fix_imagesizes_desc']                = 'Convertir automatiquement aux dimensions appropriées ou non les images qui sont insérées avec un éditeur WYSIWYG et dont les dimensions sont ajustées.';
$_lang['goodnews.settings_auto_full_urls']                          = 'Automatically convert URLs to absolute URLs';
$_lang['goodnews.settings_auto_full_urls_desc']                     = 'Whether or not URLs in email body are automatically converted to absolute URLs if necessary.';
$_lang['goodnews.settings_auto_inline_css']                         = 'Conversion automatique de CSS en styles en ligne';
$_lang['goodnews.settings_auto_inline_css_desc']                    = 'Si cette option est activée, les règles CSS intégrées de l\'en-tête du modèle de newsletter sont automatiquement converties en styles en ligne.';
$_lang['goodnews.settings_auto_cleanup_subscriptions']              = 'Autonettoyage des inscriptions';
$_lang['goodnews.settings_auto_cleanup_subscriptions_desc']         = 'Si oui ou non supprimer automatiquement les souscriptions jamais activées, ainsi que leur compte utilisateur MODX associé. Cela ne concerne que les comptes utilisateur MODX qui ont des meta-data GoodNews associées! Les comptes utilisateur MODX qui appartiennent à des groupes d\'utilisateurs MODX ne seront pas touchés!';
$_lang['goodnews.settings_auto_cleanup_subscriptions_ttl']          = 'Durée de vie jusqu\'à suppression';
$_lang['goodnews.settings_auto_cleanup_subscriptions_ttl_desc']     = 'Nombre de minutes jusqu\'à ce que les souscriptions non-activées sont supprimées. (Défaut : 360 minutes).';

$_lang['goodnews.error']                                            = 'GoodNews - Défaillance de Setup';
$_lang['goodnews.error_message_tab']                                = 'Rapport de défaillance';
$_lang['goodnews.error_message_tab_desc']                           = 'Il y a un problème dans GoodNews Setup - l\'application n\'a pas pu être démarrée.';
$_lang['goodnews.error_messages']                                   = 'Les problèmes suivants ont été détectés';
$_lang['goodnews.error_message_no_container_available']             = 'Aucun conteneur de courrier GoodNews accessible n\'est disponible. Il doit y avoir au moins un conteneur de ressources GoodNews publié et accessible dans votre arbre de ressources.';
$_lang['goodnews.error_message_unauthorized']                       = 'Accès refusé! Vous n\'avez pas le droit d\'accéder à ce conteneur de courrier GoodNews. Veuillez contacter l\'administrateur de votre site.';

$_lang['goodnews.settings_containers_none']                         = 'Aucun conteneur de resources GoodNews trouvé';
$_lang['goodnews.settings_container_id']                            = 'ID';
$_lang['goodnews.settings_container_context_key']                   = 'Contexte';
$_lang['goodnews.settings_container_pagetitle']                     = 'Nom du Conteneur de Resource';

$_lang['goodnews.settings_container_editor_groups']                 = 'Groupe Editeur du Conteneur';
$_lang['goodnews.settings_container_editor_groups_desc']            = 'Liste des groupes d\'utilisateurs MODX séparés par une virgule, qui ont accès à ce conteneur GoodNews.';
$_lang['goodnews.settings_container_mail_from']                     = 'Adresse E-Mail Expéditeur (pour emails de non-remise / Bounce)';
$_lang['goodnews.settings_container_mail_from_desc']                = 'Adresse E-Mail utilisée pour envoyer des mails et pour recevoir les messages de non-remise (Bounce).';
$_lang['goodnews.settings_container_mail_from_name']                = 'Nom de l\'expéditeur';
$_lang['goodnews.settings_container_mail_from_name_desc']           = 'Nom de l\'expéditeur utilisé pour envoyer des mails.';
$_lang['goodnews.settings_container_mail_reply_to']                 = 'Adresse E-Mail de réponse';
$_lang['goodnews.settings_container_mail_reply_to_desc']            = 'Adresse E-Mail utilisée pour recevoir des réponses aux mails envoyés.';
$_lang['goodnews.settings_container_mail_charset']                  = 'Jeu de caractères des e-mails';
$_lang['goodnews.settings_container_mail_charset_desc']             = 'Jeu de caractères par défaut pour les e-mails, par ex. "iso-8859-1" ou "UTF-8"';
$_lang['goodnews.settings_container_mail_encoding']                 = 'Encodage des e-mails';
$_lang['goodnews.settings_container_mail_encoding_desc']            = 'L\'encodage des messages. Les choix possibles: "8bit", "7bit", "binary", "base64" et "quoted-printable".';
$_lang['goodnews.settings_container_mail_bouncehandling']           = 'Gestion automatique des messages de non-remise (Bounce)';
$_lang['goodnews.settings_container_mail_bouncehandling_desc']      = 'Analyser automatiquement ou non les messsages de non-remise.';

$_lang['goodnews.settings_container_smtp_use']                      = 'Utiliser un SMTP';
$_lang['goodnews.settings_container_smtp_use_desc']                 = 'Si activé, MODX essaiera d\'utiliser le protocole SMTP pour l\'envoi des e-mails.';
$_lang['goodnews.settings_container_smtp_mandrill_service']         = 'Mandrill SMTP Service';
$_lang['goodnews.settings_container_smtp_auth']                     = 'Authentification SMTP';
$_lang['goodnews.settings_container_smtp_auth_desc']                = 'Défini l\'authentification SMTP. Utilise les options mail_smtp_user et mail_smtp_password.';
$_lang['goodnews.settings_container_smtp_user']                     = 'Utilisateur SMTP';
$_lang['goodnews.settings_container_smtp_user_desc']                = 'L\'utilisateur d\'authentification au serveur SMTP.';
$_lang['goodnews.settings_container_smtp_pass']                     = 'Mot de passe SMTP';
$_lang['goodnews.settings_container_smtp_pass_desc']                = 'Le mot de passe d\'authentification au serveur SMTP.';
$_lang['goodnews.settings_container_smtp_hosts']                    = 'SMTP Hosts + Ports';
$_lang['goodnews.settings_container_smtp_hosts_desc']               = 'Sets SMTP hosts and ports. Format: [hostname:port] (e.g., "smtp1.example.com:25;smtp2.example.com:465").';
$_lang['goodnews.settings_container_smtp_prefix']                   = 'Préfixe de connexion SMTP';
$_lang['goodnews.settings_container_smtp_prefix_desc']              = 'Défini le préfixe de connexion. Les choix sont "", "ssl" ou "tls".';
$_lang['goodnews.settings_container_smtp_keepalive']                = 'Keep-Alive SMTP';
$_lang['goodnews.settings_container_smtp_keepalive_desc']           = 'Évite que la connexion SMTP soit fermée après chaque envoi d\'e-mail. Cette option n\'est pas recommandée.';
$_lang['goodnews.settings_container_smtp_timeout']                  = 'Timeout SMTP';
$_lang['goodnews.settings_container_smtp_timeout_desc']             = 'Défini le délai en secondes du timeout de connexion au serveur SMTP. Cette fonction ne fonctionne pas sur les serveurs win32.';
$_lang['goodnews.settings_container_smtp_single_to']                = 'Simple destinataire SMTP';
$_lang['goodnews.settings_container_smtp_single_to_desc']           = 'If activated, the TO: field will process individual emails.';
$_lang['goodnews.settings_container_smtp_helo']                     = 'Message HELO de SMTP';
$_lang['goodnews.settings_container_smtp_helo_desc']                = 'Défini le messages HELO du protocole SMTP (par défaut, nom du serveur).';

$_lang['goodnews.settings_container_mail_service']                  = 'Type de compte';
$_lang['goodnews.settings_container_mail_service_desc']             = 'Type de compte du serveur mail (imap où pop3).';
$_lang['goodnews.settings_container_mail_mailhost']                 = 'Nom de serveur de mail';
$_lang['goodnews.settings_container_mail_mailhost_desc']            = 'Nom du serveur pour E-Mails entrants.';
$_lang['goodnews.settings_container_mail_mailbox_username']         = 'Nom d\'utilisateur du compte';
$_lang['goodnews.settings_container_mail_mailbox_username_desc']    = 'Nom d\'utilisateur pour accéder à la boîte mail.';
$_lang['goodnews.settings_container_mail_mailbox_password']         = 'Mot de passe du compte';
$_lang['goodnews.settings_container_mail_mailbox_password_desc']    = 'Mot de passe pour accéder à la boîte mail.';
$_lang['goodnews.settings_container_mail_boxname']                  = 'Nom de la boîte mail';
$_lang['goodnews.settings_container_mail_boxname_desc']             = 'Nom du dossier de la boîte mail (Défaut: INBOX).';
$_lang['goodnews.settings_container_mail_port']                     = 'N° du Port';
$_lang['goodnews.settings_container_mail_port_desc']                = 'Port pour accéder à la boîte mail (Défaut: 143).';
$_lang['goodnews.settings_container_mail_service_option']           = 'Option de service';
$_lang['goodnews.settings_container_mail_service_option_desc']      = 'L\'option de service pour l\'accès à la boîte (Défaut: notls).';

$_lang['goodnews.settings_container_softbounced_msg_action']        = 'Action pour les Messages Soft Bounce';
$_lang['goodnews.settings_container_softbounced_msg_action_desc']   = 'Que faire des messages Soft Bounce après leur traitement ?';
$_lang['goodnews.settings_container_softbounces_mailbox']           = 'Dossier pour les messages Soft Bounce';
$_lang['goodnews.settings_container_softbounces_mailbox_desc']      = 'Nom du dossier où déplacer les messages Soft Bounce.';
$_lang['goodnews.settings_container_max_softbounces']               = 'Décompte Max. de Soft Bounces';
$_lang['goodnews.settings_container_max_softbounces_desc']          = 'Décompte Maximum pour les messages de non-remise provisoire pour un inscrit';
$_lang['goodnews.settings_container_max_softbounces_action']        = 'Action pour décompte Max. Soft Bounces';
$_lang['goodnews.settings_container_max_softbounces_action_desc']   = 'Quelle action déclencher pour les inscrits quand le décompte max. des messages de non-remise provisoire est atteint ?';
$_lang['goodnews.settings_container_hardbounced_msg_action']        = 'Action pour Messages Hard Bounce';
$_lang['goodnews.settings_container_hardbounced_msg_action_desc']   = 'Que faire des messages de non-remise permanente après leur traitement ?';
$_lang['goodnews.settings_container_hardbounces_mailbox']           = 'Dossier pour Messages Hard Bounce';
$_lang['goodnews.settings_container_hardbounces_mailbox_desc']      = 'Nom du dossier où déplacer les Messages Hard Bounce.';
$_lang['goodnews.settings_container_max_hardbounces']               = 'Décompte Max. Hard Bounces';
$_lang['goodnews.settings_container_max_hardbounces_desc']          = 'Décompte Max. de Messages Hard Bounce pour un inscrit';
$_lang['goodnews.settings_container_max_hardbounces_action']        = 'Action pour décompte Max. Hard Bounces';
$_lang['goodnews.settings_container_max_hardbounces_action_desc']   = 'Quelle action déclencher pour les inscrits quand le décompte max. des messages de non-remise définitive est atteint ?';

$_lang['goodnews.settings_container_notclassified_msg_action']      = 'Action pour les messages non-classés';
$_lang['goodnews.settings_container_notclassified_msg_action_desc'] = 'Que faire des messages non-classés?';
$_lang['goodnews.settings_container_notclassified_mailbox']         = 'Dossier pour les messages non-classés';
$_lang['goodnews.settings_container_notclassified_mailbox_desc']    = 'Nom du dossier dans lequel déplacer les messages non-classés.';

$_lang['goodnews.settings_container_collection1_fieldset']          = 'Collection 1';
$_lang['goodnews.settings_container_collection2_fieldset']          = 'Collection 2';
$_lang['goodnews.settings_container_collection3_fieldset']          = 'Collection 3';
$_lang['goodnews.settings_container_collection_label']              = 'Label Collection';
$_lang['goodnews.settings_container_collection_label_desc']         = 'Entrer un label pour cette collection (sera utilisé comme titre dans l\'éditeur).';
$_lang['goodnews.settings_container_collection_parents']            = 'ID(s) du Conteneur';
$_lang['goodnews.settings_container_collection_parents_desc']       = 'Liste des IDs des Conteneur séparées par une virgule depuis lesquels collecter les Resources.';

$_lang['goodnews.settings_container_mail_pop3']                     = 'POP3';
$_lang['goodnews.settings_container_mail_imap']                     = 'IMAP';
$_lang['goodnews.settings_container_mail_none']                     = 'None';
$_lang['goodnews.settings_container_mail_tls']                      = 'TLS';
$_lang['goodnews.settings_container_mail_notls']                    = 'NO TLS';
$_lang['goodnews.settings_container_mail_ssl']                      = 'SSL';
$_lang['goodnews.settings_container_softbounced_msg_move']          = 'Déplacer';
$_lang['goodnews.settings_container_softbounced_msg_delete']        = 'Effacer';
$_lang['goodnews.settings_container_hardbounced_msg_move']          = 'Déplacer';
$_lang['goodnews.settings_container_hardbounced_msg_delete']        = 'Effacer';
$_lang['goodnews.settings_container_soft_subscriber_disable']       = 'Désactiver l\'inscrit';
$_lang['goodnews.settings_container_soft_subscriber_delete']        = 'Effacer l\'inscrit';
$_lang['goodnews.settings_container_hard_subscriber_disable']       = 'Désactiver l\'inscrit';
$_lang['goodnews.settings_container_hard_subscriber_delete']        = 'Effacer l\'inscrit';
$_lang['goodnews.settings_container_notclassified_msg_move']        = 'Déplacer';
$_lang['goodnews.settings_container_notclassified_msg_delete']      = 'Effacer';

$_lang['goodnews.settings_container_update']                        = 'Editer les paramètres du Conteneur';
$_lang['goodnews.settings_container_tab_general']                   = 'Général';
$_lang['goodnews.settings_container_tab_smtp']                      = 'SMTP';
$_lang['goodnews.settings_container_tab_bouncemailbox']             = 'Boîte Mail Bounce';
$_lang['goodnews.settings_container_tab_bouncerules']               = 'Règles de Bounce';
$_lang['goodnews.settings_container_tab_unclassified_bounces']      = 'Bounces non-classés';
$_lang['goodnews.settings_container_tab_resource_collection']       = 'Content Collection';
$_lang['goodnews.settings_container_err_ns_editor_groups']          = 'Indiquer au moins un groupe d\'éditeur de Conteneur.';
$_lang['goodnews.settings_container_err_ns_mail_from']              = 'Indiquer l\'adresse e-mail de l\'éxpéditeur (pour Messages de Bounce).';
$_lang['goodnews.settings_container_err_ns_mail_from_name']         = 'Indiquer le nom de l\'expéditeur.';
$_lang['goodnews.settings_container_err_ns_mail_reply_to']          = 'Indiquer l\'adresse mail de réponse.';
$_lang['goodnews.settings_container_err_ns_mail_charset']           = 'Please specify the mail charset.';
$_lang['goodnews.settings_container_err_ns_mail_encoding']          = 'Please specify the mail encoding.';
$_lang['goodnews.settings_container_err_mailbox_connection_failed'] = 'Impossible de se connecter à la boîte de Bounce. Vérifier les paramètres.';

$_lang['goodnews.import']                                           = 'GoodNews - Import';
$_lang['goodnews.import_button']                                    = 'Import';
$_lang['goodnews.import_close_button']                              = 'Fermer';
$_lang['goodnews.import_subscribers_tab']                           = 'Inscrits';
$_lang['goodnews.import_subscribers_tab_desc']                      = 'Importer des inscrits dans la base de données utilisateurs MODX. ATTENTION: Sauvegardez la base de données MODX avant de démarrer l\'import!';
$_lang['goodnews.import_subscribers_csvfile']                       = 'Fichier CSV';
$_lang['goodnews.import_subscribers_csvfile_desc']                  = 'Choisir un fichier CSV local qui contient les données à importer. Le fichier sera téléversé sur le serveur.<br><br><strong>Format CSV requis</strong>:<br>Pas de ligne d\'en-tête! | Premier champ= email, Deuxième champ = nom complet';
$_lang['goodnews.import_subscribers_csvfile_button']                = 'Choisir le fichier';
$_lang['goodnews.import_subscribers_batchsize']                     = 'Taille du lot';
$_lang['goodnews.import_subscribers_batchsize_desc']                = 'Nombre d\'enregistrements à importer. Si réglé sur 0, tous les enregistrements seront importés. Par défaut 0.';
$_lang['goodnews.import_subscribers_delimiter']                     = 'Caractère de séparation des champs';
$_lang['goodnews.import_subscribers_delimiter_desc']                = 'Définir le caractère de séparation des champs (un unique caractère). Par défaut ,';
$_lang['goodnews.import_subscribers_enclosure']                     = 'Field Enclosure Character';
$_lang['goodnews.import_subscribers_enclosure_desc']                = 'Caractère de délimitation des champs (un unique caractère). Par défaut "';
$_lang['goodnews.import_subscribers_assign_grpcat']                 = 'Attribuer des groupes de diffusion et Catégories';
$_lang['goodnews.import_subscribers_grpcat']                        = 'Groupes de diffusion et Catégories';
$_lang['goodnews.import_subscribers_update_existing']               = 'Mettre à jour les inscrits existants';
$_lang['goodnews.import_subscribers_update_existing_desc']          = 'Si activé, les abonnés existants seront mis à jour (Changer le nom complet, Ajouter des affectations de groupe et catégories). Sinon, ils seront ignorés.';
$_lang['goodnews.import_subscribers_button_start']                  = 'Débuter l\'import';
$_lang['goodnews.import_subscribers_status']                        = 'Statut de l\'import';
$_lang['goodnews.import_subscribers_msg_importing']                 = 'Importation...';
$_lang['goodnews.import_subscribers_msg_successfull']               = 'Import réussi';
$_lang['goodnews.import_subscribers_msg_failed']                    = 'Import échoué';
$_lang['goodnews.import_subscribers_log_prep_csv_import']           = 'Préparation de l\'import CSV';
$_lang['goodnews.import_subscribers_log_importing_csv']             = 'Importation du fichier CSV';
$_lang['goodnews.import_subscribers_log_batchsize']                 = 'Taille du lot: ';
$_lang['goodnews.import_subscribers_log_subscr_imported']           = 'Importés: ';
$_lang['goodnews.import_subscribers_log_subscr_updated']            = 'Mis à jour: ';
$_lang['goodnews.import_subscribers_log_err_subscr_save']           = 'Non importés. Enregistrement échoué: ';
$_lang['goodnews.import_subscribers_log_err_subscr_update']         = 'Non importés. Mise à jour échouée: ';
$_lang['goodnews.import_subscribers_log_err_duplicate_email']       = 'Non importés. Email à double: ';
$_lang['goodnews.import_subscribers_log_err_subscr_ae']             = 'Non importés. Existe déjà: ';
$_lang['goodnews.import_subscribers_log_err_subscr_data']           = 'Non importés. Mauvaises données: ';
$_lang['goodnews.import_subscribers_log_err_email_invalid']         = 'Non importés. Adresse e-mail non valide: ';
$_lang['goodnews.import_subscribers_log_ns_csvfile']                = 'Choisir un fichier CSV.';
$_lang['goodnews.import_subscribers_log_wrong_filetype']            = 'Uniquement les fichiers CSV sont acceptés.';
$_lang['goodnews.import_subscribers_log_no_class']                  = 'La classe GoodNewsImportSubscribers n\'a pas pu être instantiée.';
$_lang['goodnews.import_subscribers_log_ns_batchsize']              = 'Spécifier une taille de lot.';
$_lang['goodnews.import_subscribers_log_ns_delimiter']              = 'Spécifier un caractère de séparation.';
$_lang['goodnews.import_subscribers_log_ns_enclosure']              = 'Spécifier un caractère de délimitation.';
$_lang['goodnews.import_subscribers_log_ns_grpcat']                 = 'Choisir au moins un groupe GoodNews (ou plusieurs groupes et catégories).';
$_lang['goodnews.import_subscribers_log_finished']                  = 'Import terminé. Inscrits importés avec succès: ';
$_lang['goodnews.import_subscribers_log_failed']                    = 'Import échoué. Contrôler les messages d\'erreur.';
$_lang['goodnews.import_subscribers_log_err_open_csvfile']          = 'Erreur d\'ouverture du fichier CSV.';

$_lang['goodnews.export_button']                                    = 'Export';
$_lang['goodnews.export_subscribers']                               = 'Subscribers - Export';
$_lang['goodnews.export_subscribers_desc']                          = 'Export <b>[[+count]]</b> subscribers as CSV file based on your filter settings.';
$_lang['goodnews.export_subscribers_delimiter']                     = 'Caractère de séparation des champs';
$_lang['goodnews.export_subscribers_delimiter_desc']                = 'Définir le caractère de séparation des champs (un unique caractère). Par défaut ,';
$_lang['goodnews.export_subscribers_enclosure']                     = 'Caractère de délimitation des champs';
$_lang['goodnews.export_subscribers_enclosure_desc']                = 'Définir le caractère de délimitation des champs (un unique caractère). Par défaut "';
$_lang['goodnews.export_subscribers_button_start']                  = 'Start export';
$_lang['goodnews.export_subscribers_msg_successfull']               = ' subscribers exported successfully. Downloading file...';
$_lang['goodnews.export_subscribers_msg_ns_subscribers']            = 'There are no subscribers to export. Please check your filter settings.';
$_lang['goodnews.export_subscribers_error_page_ns_export_file']     = 'An error occurred while downloading the export file!';
$_lang['goodnews.export_subscribers_error_page_check_log']          = 'Please check the MODX error log for more details.';
$_lang['goodnews.export_subscribers_error_page_back_button']        = 'Back to GoodNews';

$_lang['setting_goodnews.current_container']                        = 'Conteneur GoodNews actuel';
$_lang['setting_goodnews.current_container_desc']                   = 'ID du Conteneur GoodNews actuel sélectionné.';
$_lang['setting_goodnews.test_subject_prefix']                      = 'Préfixe pour le Sujet des e-mail de Test';
$_lang['setting_goodnews.test_subject_prefix_desc']                 = 'Définir un texte qui sera préfixé au Sujet des e-mails de Test.';
$_lang['setting_goodnews.statusemail_enabled']                      = 'Status-Reports activated';
$_lang['setting_goodnews.statusemail_enabled_desc']                 = 'Whether or not status-reports will be sent if mailing-status changes (stopped or finished).';
$_lang['setting_goodnews.statusemail_fromname']                     = 'Name of the Sender for Status-Emails';
$_lang['setting_goodnews.statusemail_fromname_desc']                = 'Define a Name which is used for sending status-emails.';
$_lang['setting_goodnews.statusemail_chunk']                        = 'Chunk for Status-Emails';
$_lang['setting_goodnews.statusemail_chunk_desc']                   = 'Define a Chunk which is used for sending status-emails.';
$_lang['setting_goodnews.mailing_bulk_size']                        = 'Taille du lot du Mailing';
$_lang['setting_goodnews.mailing_bulk_size_desc']                   = 'Définit combien d\'e-mails sont envoyés par lot/itération.';
$_lang['setting_goodnews.worker_process_limit']                     = 'Nombre maximum de Processus d\'envoi(1-10)';
$_lang['setting_goodnews.worker_process_limit_desc']                = 'Définit le nombre maximum de processus d\'envoi parallèles à utiliser.';
$_lang['setting_goodnews.worker_process_active']                    = 'Processus d\'envoi activé';
$_lang['setting_goodnews.worker_process_active_desc']               = 'La tâche Cron peut-elle démarrer le processus d\'envoi de GoodNews? Ce paramètre peut être utilisé  pour désactiver temporairement le déclencheur Cron.';
$_lang['setting_goodnews.admin_groups']                             = 'Groupes Administrateur GoodNews';
$_lang['setting_goodnews.admin_groups_desc']                        = 'Liste des groupes d\'utilisateurs MODX séparés par une virgule, qui ont accès aux paramètres GoodNews.';
$_lang['setting_goodnews.auto_fix_imagesizes']                      = 'Ajuster automatiquement la taille des images (pThumb requis)';
$_lang['setting_goodnews.auto_fix_imagesizes_desc']                 = 'Convertir automatiquement aux dimensions appropriées ou non les images qui sont insérées avec un éditeur WYSIWYG et dont les dimensions sont ajustées.';
$_lang['setting_goodnews.auto_full_urls']                           = 'Automatically convert URLs to absolute URLs';
$_lang['setting_goodnews.auto_full_urls_desc']                      = 'Whether or not URLs in email body are automatically converted to absolute URLs if necessary.';
$_lang['setting_goodnews.auto_inline_css']                          = 'Conversion automatique de CSS en styles en ligne';
$_lang['setting_goodnews.auto_inline_css_desc']                     = 'Si cette option est activée, les règles CSS intégrées de l\'en-tête du modèle de newsletter sont automatiquement converties en styles en ligne.';
$_lang['setting_goodnews.auto_cleanup_subscriptions']               = 'Autonettoyage des inscriptions';
$_lang['setting_goodnews.auto_cleanup_subscriptions_desc']          = 'Si oui ou non supprimer automatiquement les souscriptions jamais activées ou inactives, ainsi que leur compte utilisateur MODX associé. Cela ne concerne que les comptes utilisateur MODX qui ont des meta-data GoodNews associées! Les comptes utilisateur MODX qui appartiennent à des groupes d\'utilisateurs MODX ne seront pas touchés!';
$_lang['setting_goodnews.auto_cleanup_subscriptions_ttl']           = 'Durée de vie jusqu\'à suppression';
$_lang['setting_goodnews.auto_cleanup_subscriptions_ttl_desc']      = 'Nombre de minutes jusqu\'à ce que les souscriptions non-activées sont supprimées. (Défaut : 360 minutes).';
$_lang['setting_goodnews.cron_security_key']                        = 'Clé de sécurité Cron';
$_lang['setting_goodnews.cron_security_key_desc']                   = 'S\'il vous plaît, entrez une chaîne (comme un mot de passe) aléatoire qui sera utilisée pour l\'authentification CLI Cron. Vous devez configurer votre tâche planifiée Cron  avec le paramètre CLI supplémentaires <strong> sid = [votre clé de sécurité cron] </ strong>. Il est fortement recommandé d\'ajouter une clé pour des raisons de sécurité. Laissez ce champ vide, si vous n\'avez aucune possibilité de configurer votre tâche Cron avec un paramètre supplémentaire.';
$_lang['setting_goodnews.default_container_template']               = 'Modèle par défaut pour les Conteneur GoodNews.';
$_lang['setting_goodnews.default_container_template_desc']          = 'Modèle par défaut à utiliser quand un Conteneur GoodNews est créé.';
$_lang['setting_goodnews.debug']                                    = 'GoodNews Debug Mode';
$_lang['setting_goodnews.debug_desc']                               = 'Activer / désactiver le mode Debug pour GoodNews. Si activé, des informations additionnelles seront écrites dans le journal d\'erreurs de MODX.';
